### PR TITLE
use github actions provided github token

### PR DESCRIPTION
**Pull request by justAnotherDev**
Use the GitHub provided `${{ github.token }}` as the default so the user does not need to provide one.

Example of `actions/checkout` using the same [syntax](https://github.com/actions/checkout/blob/main/action.yml#L24).

*This update does **NOT** require existing users to change anything.*

### CODE REVIEW

**Comment by kceb** [comment]
ty! @justAnotherDev

**Comment by justAnotherDev** [comment]
Nice!

Can you please update the `v1` tag so it points to the newest version (`v1.1.0`). The previous version should also get tagged as `v1.0.0`. The process shoooould be this:

**Tag previous version as `v1.0.0`**
```
git checkout master
git pull
git reset --hard HEAD~1
git tag v1.0.0
git push -u origin v1.0.0
```

**Tag current version as `v1`**
```
git checkout master
git pull
git tag -d v1
git tag v1
git push -uf origin v1
```

This way consumers can use `- uses: kceb/pull-request-url-action@v1` and always get the latest version (or specify a specific release if they desire).

You can see [`actions/checkout`](https://github.com/actions/checkout/tags) doing the same thing:

Screen Shot 2021-02-02 at 12 57 00 PM

**Comment by kceb** [comment]
@justAnotherDev I've tagged it as v1.1.0 per semver

https://github.com/kceb/pull-request-url-action/releases/tag/v1.1.0

is there any reason you are unable to update your CI builds to point to the newer minor version?

**Comment by justAnotherDev** [comment]
I can point to the minor version, just trying to follow the best practices that are being done by the GitHub provided actions. I tend to use `actions/checkout` as the "Gold Standard" since it is used by nearly every repository.

`actions/checkout` has constant minor version updates so they follow the idea of making it so the major version tag (`v1`, `v2`, etc) is always pointing to the latest version of that major version. This way you can always get the most up to date code of that major version by simply doing:

```
- uses: actions/checkout@v2
```

but the nice thing about it is you can also specify exactly which minor version you want as well if need be:

```
- uses: actions/checkout@v2.3.1
```

**Comment by kceb** [comment]
@justAnotherDev done

**Comment by justAnotherDev** [comment]
awesome, thanks a bunch!

**Pull request merged**
